INSERT INTO customer (firstname, surname) VALUES ('Nettie', 'Bowes');
INSERT INTO customer (firstname, surname) VALUES ('Robson', 'Bullock');
INSERT INTO customer (firstname, surname) VALUES ('Scarlet', 'Devine');
INSERT INTO customer (firstname, surname) VALUES ('Shah', 'O''Sullivan');
INSERT INTO customer (firstname, surname) VALUES ('Cade', 'Fitzgerald');
INSERT INTO customer (firstname, surname) VALUES ('Ernie', 'Draper');
INSERT INTO customer (firstname, surname) VALUES ('Dominika', 'Pineda');
INSERT INTO customer (firstname, surname) VALUES ('Clark', 'Hull');
INSERT INTO customer (firstname, surname) VALUES ('Shayna', 'Leech');
INSERT INTO customer (firstname, surname) VALUES ('Tiago', 'Dunlap');
INSERT INTO customer (firstname, surname) VALUES ('Enrique', 'Mayo');
INSERT INTO customer (firstname, surname) VALUES ('Reilly', 'Sharma');
INSERT INTO customer (firstname, surname) VALUES ('Manon', 'Snyder');
INSERT INTO customer (firstname, surname) VALUES ('Sapphire', 'Cotton');
INSERT INTO customer (firstname, surname) VALUES ('Bruno', 'Ellison');
INSERT INTO customer (firstname, surname) VALUES ('Tanner', 'Holding');
INSERT INTO customer (firstname, surname) VALUES ('Lennie', 'Heaton');
INSERT INTO customer (firstname, surname) VALUES ('Floyd', 'Yoder');
INSERT INTO customer (firstname, surname) VALUES ('Rosanna', 'Justice');
INSERT INTO customer (firstname, surname) VALUES ('Julian', 'Davis');
INSERT INTO customer (firstname, surname) VALUES ('Rui', 'Fraser');
INSERT INTO customer (firstname, surname) VALUES ('Kirstin', 'Ahmad');
INSERT INTO customer (firstname, surname) VALUES ('Hammad', 'Mclellan');
INSERT INTO customer (firstname, surname) VALUES ('Matei', 'Harwood');
INSERT INTO customer (firstname, surname) VALUES ('Aaminah', 'Harrell');
INSERT INTO customer (firstname, surname) VALUES ('Hashim', 'Nixon');
INSERT INTO customer (firstname, surname) VALUES ('Nayla', 'Blundell');
INSERT INTO customer (firstname, surname) VALUES ('Aimee', 'Bennett');
INSERT INTO customer (firstname, surname) VALUES ('Cairon', 'Dillon');
INSERT INTO customer (firstname, surname) VALUES ('Bridie', 'Banks');
INSERT INTO customer (firstname, surname) VALUES ('Maryam', 'Kaur');
INSERT INTO customer (firstname, surname) VALUES ('Franciszek', 'Wilkes');
INSERT INTO customer (firstname, surname) VALUES ('Adnan', 'Bourne');
INSERT INTO customer (firstname, surname) VALUES ('Cristiano', 'Bowler');
INSERT INTO customer (firstname, surname) VALUES ('Oisin', 'Prince');
INSERT INTO customer (firstname, surname) VALUES ('Imaan', 'Silva');
INSERT INTO customer (firstname, surname) VALUES ('Keely', 'Talbot');
INSERT INTO customer (firstname, surname) VALUES ('Eilidh', 'Delacruz');
INSERT INTO customer (firstname, surname) VALUES ('Sophia', 'Parker');
INSERT INTO customer (firstname, surname) VALUES ('Timothy', 'Arias');
INSERT INTO customer (firstname, surname) VALUES ('Gino', 'Roach');
INSERT INTO customer (firstname, surname) VALUES ('Rhiann', 'Talley');
INSERT INTO customer (firstname, surname) VALUES ('Faith', 'Carr');
INSERT INTO customer (firstname, surname) VALUES ('Mahir', 'Kramer');
INSERT INTO customer (firstname, surname) VALUES ('Winnie', 'Walton');
INSERT INTO customer (firstname, surname) VALUES ('Perry', 'Major');
INSERT INTO customer (firstname, surname) VALUES ('Chance', 'Estrada');
INSERT INTO customer (firstname, surname) VALUES ('Nakita', 'Hobbs');
INSERT INTO customer (firstname, surname) VALUES ('Claire', 'Eastwood');
INSERT INTO customer (firstname, surname) VALUES ('Luka', 'Kennedy');
INSERT INTO customer (firstname, surname) VALUES ('Ceara', 'Houston');
INSERT INTO customer (firstname, surname) VALUES ('Jack', 'Durham');
INSERT INTO customer (firstname, surname) VALUES ('Kaira', 'Charles');
INSERT INTO customer (firstname, surname) VALUES ('Miah', 'Petty');
INSERT INTO customer (firstname, surname) VALUES ('Aaran', 'Snow');
INSERT INTO customer (firstname, surname) VALUES ('Terrence', 'Lowry');
INSERT INTO customer (firstname, surname) VALUES ('Sameer', 'Hooper');
INSERT INTO customer (firstname, surname) VALUES ('Asiyah', 'Vickers');
INSERT INTO customer (firstname, surname) VALUES ('Tyra', 'Piper');
INSERT INTO customer (firstname, surname) VALUES ('Pranav', 'Amos');
INSERT INTO customer (firstname, surname) VALUES ('Lavinia', 'Barajas');
INSERT INTO customer (firstname, surname) VALUES ('Chyna', 'Gardiner');
INSERT INTO customer (firstname, surname) VALUES ('Tre', 'Dodd');
INSERT INTO customer (firstname, surname) VALUES ('Ayaana', 'Wheatley');
INSERT INTO customer (firstname, surname) VALUES ('Trent', 'Wiggins');
INSERT INTO customer (firstname, surname) VALUES ('Eduardo', 'Fernandez');
INSERT INTO customer (firstname, surname) VALUES ('Rebekka', 'Whittaker');
INSERT INTO customer (firstname, surname) VALUES ('Yvette', 'Burton');
INSERT INTO customer (firstname, surname) VALUES ('Sarah', 'Irving');
INSERT INTO customer (firstname, surname) VALUES ('Tyriq', 'Khan');
INSERT INTO customer (firstname, surname) VALUES ('Eleanor', 'Matthews');
INSERT INTO customer (firstname, surname) VALUES ('Malachy', 'Avalos');
INSERT INTO customer (firstname, surname) VALUES ('Campbell', 'Lambert');
INSERT INTO customer (firstname, surname) VALUES ('Luke', 'Kerr');
INSERT INTO customer (firstname, surname) VALUES ('Asif', 'Head');
INSERT INTO customer (firstname, surname) VALUES ('Ricky', 'Currie');
INSERT INTO customer (firstname, surname) VALUES ('Anam', 'Monaghan');
INSERT INTO customer (firstname, surname) VALUES ('Montell', 'Power');
INSERT INTO customer (firstname, surname) VALUES ('Lylah', 'Partridge');
INSERT INTO customer (firstname, surname) VALUES ('Lacey', 'Sanford');
INSERT INTO customer (firstname, surname) VALUES ('Bradley', 'Mcgrath');
INSERT INTO customer (firstname, surname) VALUES ('Manal', 'Dougherty');
INSERT INTO customer (firstname, surname) VALUES ('Zaki', 'Leigh');
INSERT INTO customer (firstname, surname) VALUES ('Zayn', 'Lopez');
INSERT INTO customer (firstname, surname) VALUES ('Lacy', 'Barber');
INSERT INTO customer (firstname, surname) VALUES ('Mikolaj', 'Simpson');
INSERT INTO customer (firstname, surname) VALUES ('Jordon', 'Oakley');
INSERT INTO customer (firstname, surname) VALUES ('Abby', 'Reid');
INSERT INTO customer (firstname, surname) VALUES ('Sanjay', 'Woodward');
INSERT INTO customer (firstname, surname) VALUES ('Yousif', 'Doherty');
INSERT INTO customer (firstname, surname) VALUES ('Sophia-Rose', 'Thornton');
INSERT INTO customer (firstname, surname) VALUES ('Ksawery', 'Miles');
INSERT INTO customer (firstname, surname) VALUES ('Hussain', 'Burrows');
INSERT INTO customer (firstname, surname) VALUES ('Chandler', 'Craft');
INSERT INTO customer (firstname, surname) VALUES ('Manha', 'Perry');
INSERT INTO customer (firstname, surname) VALUES ('Arran', 'Edge');
INSERT INTO customer (firstname, surname) VALUES ('Poppy-Mae', 'Whittle');
INSERT INTO customer (firstname, surname) VALUES ('Elspeth', 'Keith');
INSERT INTO customer (firstname, surname) VALUES ('Ioana', 'Oliver');
INSERT INTO customer (firstname, surname) VALUES ('Ellie-Rose', 'Lane');

INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (1, 'Havichhorster Mühle',  104, 19230,  'Setzin', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (1, 'An den Mühlen',  58, 56651,  'Niederzissen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (1, 'Soester Str.',  150, 10557,  'Berlin', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (2, 'Am Ziegelofen',  91, 56759,  'Kalenborn', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (2, 'Rosenplatz',  195, 26937,  'Stadland', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (2, 'Rottkamp',  177, 24351,  'Thumby', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (3, 'Im Sonnentau',  56, 56412,  'Untershausen', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (3, 'Am Römerhof', 128, 21730,  'Balje', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (3, 'Düesbergweg',  174, 72655,  'Altdorf', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (4, 'Unter Kahlenhausen',  11, 53115,  'Bonn', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (4, 'Am Oedingteich',  40, 24790,  'Schülldorf', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (4, 'Röttgensweg',  89, 83558,  'Maitenbeth', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (5, 'Königsberger Str.',  196, 55437,  'Nieder-Hilbersheim', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (5, 'Werseblick',  139, 23843,  'Neritz', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (5, 'An den Mühlen',  145, 54673,  'Muxerath', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (6, 'Morthorststr.', 178, 26723,  'Emden', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (6, 'Hoove',  77, 36433,  'Bad Salzungen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (6, 'Erpeler Str.', 123, 67368,  'Westheim', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (7, 'Lammerbach', 35, 19065,  'Raben Steinfeld', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (7, 'Dammstr.', 188, 54619,  'Großkampenberg', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (7, 'Altenhofer Weg',  25, 75177,  'Pforzheim', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (8, 'Mecklenbecker Str.',  53, 78078,  'Niedereschach', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (8, 'Unter Kahlenhausen',  128, 84152,  'Mengkofen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (8, 'Rohrkampstr.',  80, 95682,  'Brand', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (9, 'Liboristr.',  141, 96268,  'Mitwitz', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (9, 'Nieland',  7, 65183,  'Wiesbaden', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (9, 'Jakobusstr.',  138, 15732,  'Eichwalde', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (10, 'Sternstr.',  177, 49205,  'Hasbergen', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (10, 'Manfred-von-Richthofen-Str.',  96, 55758,  'Breitenthal', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (10, 'Marientalstr.',  185, 33129,  'Boke', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (11, 'Paul-Engelhard-Weg',  112, 52499,  'Baesweiler', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (11, 'Tondernstr.',  84, 72184,  'Eutingen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (11, 'Klinkkampweg', 7, 19288,  'Alt Krenzlin', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (12, 'Nerzweg',  158, 86862,  'Lamerdingen', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (12, 'Methweg',  199, 55758,  'Asbach', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (12, 'Magdalenenstr.',  53, 31135,  'Hildesheim', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (13, 'Telemannstr.',  192, 56348,  'Dörscheid', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (13, 'Ulmenweg',  179, 91590,  'Bruckberg', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (13, 'Paul-Engelhard-Weg',  8, 6618,  'Utenbach', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (14, 'Meinertzstr.',  91, 4347,  'Leipzig', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (14, 'Zum Burgschemm',  91, 49767,  'Twist', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (14, 'Beuelsweg',  40, 89597,  'Hausen am Bussen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (15, 'Rüschhausweg',  51, 6237,  'Spergau', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (15, 'Fresnostr.',  155, 3238,  'Lichterfeld-Schacksdorf', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (15, 'Südstr.',  85, 79106,  'Freiburg', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (16, 'Hacklenburg',  43, 25856,  'Hattstedtermarsch', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (16, 'Gremmendorfer Weg',  105, 66540,  'Neunkirchen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (16, 'Südstr.',  173, 18276,  'Kuhs', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (17, 'Bünkamp',  11, 55234,  'Kettenheim', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (17, 'Gleueler Str.',  51, 24306,  'Wittmoldt', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (17, 'Nauheimer Str.',  49, 85290,  'Geisenfeld', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (18, 'Telgenweg',  36, 19077,  'Lübesse', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (18, 'Geiststr.',  39, 97258,  'Oberickelsheim', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (18, 'Weserstr.', 129, 83679,  'Sachsenkam', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (19, 'Königsberger Str.',  124, 17111,  'Kentzlin', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (19, 'Merheimer Str.',  103, 72355,  'Schömberg', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (19, 'Wiedehagen',  194, 73035,  'Göppingen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (20, 'Nieland', 142, 3052,  'Cottbus', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (20, 'Wildpfad',  89, 22949,  'Ammersbek', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (20, 'Carossastr.',  166, 54668,  'Ernzen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (21, 'Hansaring',  196, 24361,  'Damendorf', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (21, 'Speestr.',  133, 27580,  'Bremerhaven', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (21, 'Dortmunder Str.',  77, 29386,  'Dedelstorf', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (22, 'Olpener Str.',  70, 94345,  'Aholfing', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (22, 'Soester Str.',  164, 56759,  'Kalenborn', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (22, 'Pankokstr.',  55, 21388,  'Soderstorf', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (23, 'Gustav-Tweer-Weg',  21, 76470,  'Ötigheim', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (23, 'Erpeler Str.',  182, 91487,  'Vestenbergsgreuth', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (23, 'Schützenstr.',  10, 24799,  'Friedrichsholm', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (24, 'Rinkerodeweg',  116, 55629,  'Weitersborn', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (24, 'Berrischstr.',  53, 55234,  'Hangen-Weisheim', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (24, 'Innsbruckweg',  60, 56584,  'Meinborn', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (25, 'Röttgensweg',  61, 85057,  'Ingolstadt', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (25, 'Rektoratsweg',  151, 84571,  'Reischach', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (25, 'Telgenweg',  66, 84539,  'Ampfing', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (26, 'Stettiner Str.',  136, 91282,  'Betzenstein', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (26, 'Telemannstr.',  1, 46514,  'Schermbeck', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (26, 'Ossenkampstiege',  37, 99625,  'Großneuhausen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (27, 'Stolbergstr.',  80, 83119,  'Obing', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (27, 'Friedrich-Ebert-Str.',  163, 41515,  'Grevenbroich', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (27, 'Nerzweg',  39, 23847,  'Bliestorf', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (28, 'Holunderweg',  143, 90518,  'Altdorf', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (28, 'Buldernweg',  78, 67059,  'Ludwigshafen am Rhein', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (28, 'Steinfurter Str.',  32, 25980,  'Sylt-Ost', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (29, 'Geiststr.',  107, 6803,  'Greppin', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (29, 'Piusstr.',  167, 76891,  'Niederschlettenbach', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (29, 'Werseblick',  156, 27624,  'Elmlohe', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (30, 'Weißenburgstr.',  80, 35080,  'Bad Endbach', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (30, 'Wildpfad',  76, 24238,  'Martensrade', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (30, 'Steinkamp',  38, 90513,  'Zirndorf', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (31, 'Dreilinden',  69, 96352,  'Wilhelmsthal', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (31, 'Handorfer Str.',  172, 24793,  'Bargstedt', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (31, 'Parkallee',  123, 83259,  'Schleching', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (32, 'Florentine-Eichler-Str.',  5, 90766,  'Fürth', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (32, 'Albachtener Str.',  152, 35586,  'Wetzlar', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (32, 'Hölkenbusch',  5, 72285,  'Pfalzgrafenweiler', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (33, 'Widdeshover Weg',  48, 26919,  'Brake', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (33, 'Schützenstr.',  126, 85084,  'Reichertshofen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (33, 'Flaßkuhl',  182, 73092,  'Heiningen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (34, 'Piusstr.',  14, 82279,  'Eching am Ammersee', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (34, 'Fresnostr.', 19, 34308,  'Bad Emstal', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (34, 'Geiststr.', 25, 95460,  'Bad Berneck', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (35, 'Werkstattstr.',  1, 69124,  'Heidelberg', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (35, 'Kreuzstr.',  159, 16775,  'Sonnenberg', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (35, 'Hensenstr.',  162, 55491,  'Niederweiler', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (36, 'Baumberger Str.',  84, 67308,  'Zellertal', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (36, 'Mindener Str.',  66, 86558,  'Hohenwart', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (36, 'Dorotheenstr.',  118, 77955,  'Ettenheim', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (37, 'Südstr.',  110, 55578,  'Wolfsheim', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (37, 'Catharina-Müller-Str.',  9, 83093,  'Bad Endorf', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (37, 'Am Berler Kamp',  39, 88693,  'Deggenhausertal', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (38, 'Goebenstr.',  131, 23847,  'Lasbek', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (38, 'Wildpfad',  182, 35321,  'Laubach', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (38, 'Ostmarkstr.',  52, 54331,  'Pellingen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (39, 'Langestr.',  60, 58809,  'Neuenrade', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (39, 'Hogenbergstr.',  30, 95179,  'Geroldsgrün', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (39, 'Manfred-von-Richthofen-Str.',  118, 24392,  'Boren', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (40, 'Zülpicher Str.',  86, 64405,  'Fischbachtal', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (40, 'Marientalstr.',  54, 8393,  'Meerane', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (40, 'Werkstattstr.',  135, 25712,  'Hochdonn', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (41, 'Liboristr.',  197, 55430,  'Urbar', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (41, 'Zülpicher Str.',  15, 56355,  'Bettendorf', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (41, 'Dahlienweg',  58, 23744,  'Schönwalde am Bungsberg', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (42, 'Merheimer Str.',  90, 54649,  'Mauel', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (42, 'Nerzweg',  10, 17349,  'Schönbeck', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (42, 'Hansaring',  57, 37434,  'Krebeck', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (43, 'Overbergstr.',  28, 44807,  'Bochum', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (43, 'Angelstr.',  97, 6749,  'Bitterfeld', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (43, 'Nienkamp',  9, 67378,  'Zeiskam', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (44, 'Cheruskerstr.',  189, 78737,  'Fluorn-Winzeln', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (44, 'Agrippastr.',  188, 9306,  'Thalheim', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (44, 'Nieland',  63, 29378,  'Wittingen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (45, 'Maximilianstr.',  42, 18528,  'Patzig', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (45, 'Salzmannstr.',  189, 80935,  'München', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (45, 'Simon-Meister-Str.',  32, 23816,  'Groß Niendorf', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (46, 'Rennbahnstr.',  187, 24407,  'Rabenkirchen-Faulück', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (46, 'Hansaring',  151, 55595,  'Bockenau', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (46, 'Försterstr.',  11, 74182,  'Obersulm', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (47, 'Olpener Str.',  48, 55606,  'Heimweiler', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (47, 'Eifelstr.',  19, 79697,  'Wies', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (47, 'Düsseldorfer Str.',  193, 48151,  'Münster', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (48, 'Altenhofer Weg',  155, 53426,  'Dedenbach', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (48, 'Marientalstr.',  163, 21502,  'Worth', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (48, 'Straßburger Weg',  34, 76744,  'Vollmersweiler', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (49, 'Am Grauen Stein',  79, 31226,  'Peine', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (49, 'Berrischstr.',  181, 44143,  'Dortmund', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (49, 'Angelmodder Weg',  188, 25336,  'Elmshorn', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (50, 'Hofstr.',  172, 31621,  'Pennigsehl', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (50, 'Hensenstr.',  97, 54634,  'Niederstedem', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (50, 'Rennbahnstr.',  198, 66879,  'Kollweiler', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (51, 'Am Römerhof',  75, 34477,  'Berndorf', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (51, 'Kurze Str.',  6, 34314,  'Espenau', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (51, 'Am Ziegelofen',  55, 33142,  'Büren', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (52, 'Handorfer Str.',  200, 45964,  'Gladbeck', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (52, 'Kirchstr.',  52, 83224,  'Staudach-Egerndach', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (52, 'Oberschlesier Str.',  107, 67806,  'Dörrmoschel', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (53, 'Bielefelder Str.',  63, 25938,  'Wrixum', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (53, 'Ölbergstr.',  21, 87527,  'Ofterschwang', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (53, 'Handorfer Str.', 24, 54636,  'Oberweiler', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (54, 'Kappenberger Damm',  105, 1157,  'Dresden', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (54, 'Eibenweg',  8, 84508,  'Burgkirchen an der Alz', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (54, 'Hindenburgplatz',  83, 82395,  'Obersöchering', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (55, 'Schmittingheide', 75, 84107,  'Weihmichl', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (55, 'Dortmunder Str.',  54, 86981,  'Kinsau', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (55, 'Idenbrockplatz',  91, 48465,  'Samern', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (56, 'Von-der-Tinnen-Str.',  131, 85661,  'Forstinning', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (56, 'Wolbecker Str.',  10, 76698,  'Ubstadt-Weiher', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (56, 'Johanniterstr.',  4, 37445,  'Walkenried', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (57, 'Theodor-Heuss-Ring',  119, 37194,  'Wahlsburg', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (57, 'Schützenstr.',  94, 48712,  'Gescher', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (57, 'Augustastr.',  81, 52349,  'Düren', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (58, 'Cheruskerstr.',  79, 66484,  'Großsteinhausen', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (58, 'Angelstr.',  101, 66885,  'Bedesbach', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (58, 'Meckmannweg',  171, 57612,  'Idelberg', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (59, 'Königsberger Str.',  20, 83253,  'Rimsting', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (59, 'Grevener Str.',  77, 56357,  'Rettershain', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (59, 'Düsseldorfer Str.',  44, 56767,  'Mosbruch', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (60, 'Dahlienweg', 34, 70567,  'Stuttgart', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (60, 'Maximilianstr.',  33, 21710,  'Engelschoff', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (60, 'Am Nubbenberg', 165, 3,  12053, false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (61, 'Dingbängerweg',  69, 17219,  'Groß Flotow', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (61, 'Försterstr.',  48, 65558,  'Holzheim', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (61, 'Zum Guten Hirten',  70, 71131,  'Oberjettingen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (62, 'Erikahof',  10, 74933,  'Neidenstein', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (62, 'Mariendorfer Str.',  10, 54310,  'Ralingen an der Sauer', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (62, 'Düesbergweg',  69, 73655,  'Alfdorf', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (63, 'Mersmannsstiege',  167, 85395,  'Wolfersdorf', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (63, 'Birkenweg',  32, 26789,  'Leer', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (63, 'Dorbaumstr.',  192, 24646,  'Warder', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (64, 'Kempener Str.',  37, 55487,  'Dill', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (64, 'Magdalenenstr.',  35, 21493,  'Sahms', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (64, 'Berrischstr.',  34, 56237,  'Breitenau', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (65, 'Flaßkuhl',  27, 53949,  'Dahlem', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (65, 'Piusstr.',  135, 57629,  'Luckenbach', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (65, 'Friedrichstr.',  127, 24537,  'Neumünster', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (66, 'Soetenkamp',  34, 42799,  'Leichlingen', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (66, 'Kreuzstr.',  177, 24625,  'Großharrie', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (66, 'Florentine-Eichler-Str.',  77, 57632,  'Ziegenhain', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (67, 'Johann-Krane-Weg',  150, 94256,  'Drachselsried', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (67, 'Hofstr.',  121, 55583,  'Bad Münster am Stein-Ebernburg', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (67, 'Mecklenbecker Str.', 142, 19073,  'Klein Rogahn', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (68, 'Stolbergstr.',  55, 86462,  'Langweid am Lech', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (68, 'Enschedeweg',  81, 55595,  'Weinsheim', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (68, 'Steinkamp',  188, 82547,  'Eurasburg', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (69, 'Stolbergstr.',  61, 6556,  'Mönchpfiffel-Nikolausrieth', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (69, 'Theodor-Heuss-Ring',  102, 73463,  'Westhausen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (69, 'An den Mühlen',  94, 78187,  'Geisingen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (70, 'Kapellenstr.',  96, 17111,  'Sarow', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (70, 'Berrischstr.',  67, 17111,  'Hohenbollentin', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (70, 'Münsterstr.',  55, 91126,  'Rednitzhembach', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (71, 'Nienkamp',  40, 57636,  'Sörth', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (71, 'Magdalenenstr.',  186, 6844,  'Dessau', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (71, 'Geiststr.',  153, 84332,  'Hebertsfelden', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (72, 'Pankokstr.',  184, 23858,  'Reinfeld', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (72, 'Nienkamp',  182, 46047,  'Oberhausen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (72, 'Cheruskerstr.',  70, 59939,  'Olsberg', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (73, 'Im Draum', 125, 69514,  'Laudenbach', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (73, 'Zülpicher Str.',  107, 87484,  'Nesselwang', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (73, 'Kochwiesenstr.',  142, 65223,  'Taunusstein', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (74, 'Bernhard-Poether-Str.',  79, 46414,  'Rhede', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (74, 'Methweg',  124, 27419,  'Lengenbostel', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (74, 'Kösliner Str.',  23, 63110,  'Rodgau', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (75, 'Carossastr.',  104, 56370,  'Dörsdorf', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (75, 'Ölbergstr.',  23, 99947,  'Behringen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (75, 'Mecklenbecker Str.',  162, 78664,  'Eschbronn', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (76, 'Hölkenbusch',  198, 24395,  'Nieby', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (76, 'Marsweg',  54, 25569,  'Hodorf', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (76, 'Parkallee',  64, 97499,  'Donnersdorf', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (77, 'Kröver Str.',  129, 99976,  'Unstruttal', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (77, 'Hahnenstr.',  118, 24582,  'Wattenbek', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (77, 'Dodostr.',  72, 57614,  'Borod', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (78, 'Gropiusstr.',  79, 83088,  'Kiefersfelden', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (78, 'Josef-Suwelack-Weg',  115, 17390,  'Ziethen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (78, 'Mecklenbecker Str.',  8, 33129,  'Boke', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (79, 'Sanddornweg',  18, 53539,  'Welcherath', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (79, 'Magdalenenstr.',  16, 33106,  'Paderborn', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (79, 'Janningsweg',  171, 97491,  'Aidhausen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (80, 'Ulmenweg',  191, 24105,  'Kiel', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (80, 'Von-der-Tinnen-Str.',  153, 86514,  'Ustersbach', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (80, 'Agrippastr.',  12, 84431,  'Rattenkirchen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (81, 'Albachtener Str.',  16, 57258,  'Freudenberg', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (81, 'Grevener Str.',  162, 55606,  'Meckenbach', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (81, 'Rüschhausweg',  100, 23970,  'Wismar', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (82, 'Deutz-Kalker Str.',  49, 84187,  'Weng', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (82, 'Altenhofer Weg',  71, 82178,  'Puchheim', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (82, 'Ulmenweg',  21, 65812,  'Bad Soden am Taunus', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (83, 'Kösliner Str.',  193, 71739,  'Oberriexingen', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (83, 'Paul-Engelhard-Weg',  136, 63768,  'Hösbach', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (83, 'Dachsleite',  177, 40211,  'Düsseldorf', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (84, 'Gottesweg',  174, 48432,  'Rheine', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (84, 'Drachterstr.',  79, 57581,  'Katzwinkel', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (84, 'Am Berler Kamp',  165, 86869,  'Oberostendorf', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (85, 'Röttgensweg',  103, 55758,  'Oberreidenbach', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (85, 'Mecklenbecker Str.',  158, 56288,  'Korweiler', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (85, 'Max-Winkelmann-Str.',  12, 6295,  'Burgsdorf', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (86, 'Sophienstr.',  8, 54673,  'Zweifelscheid', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (86, 'Erikahof',  95, 86750,  'Megesheim', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (86, 'Weseler Str.',  132, 39114,  'Magdeburg', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (87, 'Im Draum',  89, 19288,  'Lüblow', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (87, 'Friedrichstr.',  6, 9306,  'Königsfeld', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (87, 'Immelmannstr.',  180, 53111,  'Bonn', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (88, 'Skagerrakstr.',  40, 54518,  'Hupperath', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (88, 'Hahnenstr.',  18, 21279,  'Hollenstedt', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (88, 'Böttcherstr.', 4, 24848,  'Klein Rheide', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (89, 'Wormser Str.', 123, 86926,  'Greifenberg', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (89, 'Soetenkamp',  51, 67822,  'Mannweiler-Cölln', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (89, 'Augustastr.',  45, 37308,  'Bodenrode-Westhausen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (90, 'Hoove',  101, 83536,  'Gars am Inn', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (90, 'Sophienstr.',  130, 55234,  'Erbes-Büdesheim', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (90, 'Offenbergstr.', 18, 74542,  'Braunsbach', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (91, 'Skagerrakstr.',  123, 38640,  'Goslar', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (91, 'Gropiusstr.',  192, 54619,  'Reiff', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (91, 'Stettiner Str.',  170, 54636,  'Trimport', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (92, 'Kappenberger Damm',  181, 7749,  'Jena', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (92, 'Offenbergstr.',  5, 94405,  'Landau an der Isar', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (92, 'Straßburger Weg',  155, 91088,  'Bubenreuth', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (93, 'Düesbergweg',  61, 17235,  'Neustrelitz', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (93, 'Rinscheweg',  70, 53225,  'Bonn', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (93, 'Parkallee',  21, 10439,  'Berlin', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (94, 'Parkallee',  188, 74238,  'Krautheim', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (94, 'Merheimer Str.',  81, 67808,  'Ruppertsecken', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (94, 'Marientalstr.',  71, 71638,  'Ludwigsburg', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (95, 'Kreuzstr.', 107, 6449,  'Groß Schierstedt', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (95, 'Stolbergstr.',  100, 87494,  'Rückholz', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (95, 'Rinscheweg',  86, 30657,  'Hannover', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (96, 'Magdalenenstr.',  163, 85609,  'Aschheim', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (96, 'Schiffahrter Damm',  91, 25590,  'Osterstedt', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (96, 'Catharina-Müller-Str.',  22, 89197,  'Weidenstetten', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (97, 'Max-Winkelmann-Str.',  32, 26721,  'Emden', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (97, 'Agrippastr.',  80, 21514,  'Büchen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (97, 'Overbergstr.',  23, 29575,  'Altenmedingen', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (98, 'Methweg',  14, 56659,  'Burgbrohl', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (98, 'Sophienstr.',  158, 97350,  'Mainbernheim', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (98, 'Von-Holte-Str.',  123, 24806,  'Hohn', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (99, 'Scheibenstr.',  199, 74632,  'Neuenstein', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (99, 'Sternstr.',  34, 49843,  'Gölenkamp', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (99, 'Beuelsweg',  151, 42113,  'Wuppertal', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (100, 'Friedrich-Ebert-Str.',  9, 61191,  'Rosbach vor der Höhe', true);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (100, 'Am Blütenhain',  93, 44137,  'Dortmund', false);
INSERT INTO address (customerid, street, streetno, zip, city, ispostaladdress) VALUES (100, 'Wollinstr.',  78, 92442,  'Wackersdorf', false);